[package]
name = "momos_aedes"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
numpy = "0.21"
ndarray = "0.16.1"

[package.metadata.maturin]
name = "momos_aedes"
